[program:payroll-default]
process_name=%(program_name)s_%(process_num)02d
command=php {{APP_DIR}}/artisan queue:work --queue=default --tries=1 --timeout=0
directory={{APP_DIR}}
user=www-data
numprocs=1
autostart=true
autorestart=true
startsecs=3
startretries=3
stopwaitsecs=3600
stderr_logfile={{LOG_DIR}}/payroll-default-stderr.log
stdout_logfile={{LOG_DIR}}/payroll-default-stdout.log
environment=APP_ENV="production"

[program:payroll-email]
process_name=%(program_name)s_%(process_num)02d
command=php {{APP_DIR}}/artisan queue:work --queue=email --tries=3 --timeout=300
directory={{APP_DIR}}
user=www-data
numprocs=2
autostart=true
autorestart=true
startsecs=3
startretries=3
stopwaitsecs=600
stderr_logfile={{LOG_DIR}}/payroll-email-stderr.log
stdout_logfile={{LOG_DIR}}/payroll-email-stdout.log
environment=APP_ENV="production"
